# Generated by Django 4.1.7 on 2023-03-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('plat_cd', models.IntegerField(blank=True, null=True)),
                ('scores', models.FloatField(blank=True, null=True)),
                ('day', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('regist', models.CharField(blank=True, max_length=255, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.CharField(blank=True, max_length=255, null=True)),
                ('type_cd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('bookmark_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_mark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_cd', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('hit_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'hit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBasedcfmodel',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('recommend_book_no_list', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_basedcfmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('read_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'read_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('image_url', models.CharField(blank=True, max_length=512, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=20, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('favorite_novel_genre', models.CharField(blank=True, max_length=255, null=True)),
                ('favorite_webtoon_genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBasedCfByAgeGenderModel',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField()),
                ('modified_dt', models.DateTimeField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('book_no_list', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('type_cd', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_based_cf_by_age_gender_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBasedCfModel',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
                ('book_no_list', models.TextField(blank=True, null=True)),
                ('type_cd', models.IntegerField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('modified_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_based_cf_model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPredictedGradeModel',
            fields=[
                ('pred_grade_no', models.AutoField(primary_key=True, serialize=False)),
                ('pridict_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_predicted_grade_model',
                'managed': False,
            },
        ),
    ]
